
import 'package:flutter/material.dart';
import 'package:movieapp/core/app_export.dart';

import '../models/ticket_item_model.dart';

// ignore: must_be_immutable
class TicketItemWidget extends StatelessWidget {
  TicketItemWidget(
    this.sixItemModelObj, {
    Key? key,
  }) : super(
          key: key,
        );

  TicketItemModel sixItemModelObj;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: EdgeInsets.symmetric(
        horizontal: 51.h,
        vertical: 16.v,
      ),
      decoration: AppDecoration.outlinePrimary.copyWith(
        borderRadius: BorderRadiusStyle.roundedBorder10,
      ),
      width: 249.h,
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Container(
            height: 15.v,
            width: 144.h,
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(
                72.h,
              ),
              border: Border.all(
                color: theme.colorScheme.primary,
                width: 1.h,
              ),
              gradient: LinearGradient(
                begin: Alignment(0.5, 0),
                end: Alignment(0.5, 0.14),
                colors: [
                  theme.colorScheme.primary.withOpacity(0.3),
                  theme.colorScheme.primary.withOpacity(0.3),
                ],
              ),
            ),
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 8.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 8.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
            ],
          ),
          SizedBox(height: 4.v),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 8.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 8.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
            ],
          ),
          SizedBox(height: 4.v),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatTealA40001,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 8.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatTealA40001,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatTealA40001,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatTealA40001,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 8.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
            ],
          ),
          SizedBox(height: 4.v),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 8.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 8.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
            ],
          ),
          SizedBox(height: 4.v),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPink300,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 8.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPink300,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPink300,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPink300,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 8.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
            ],
          ),
          SizedBox(height: 4.v),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 8.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatDeepPurple600,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatDeepPurple600,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 8.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
            ],
          ),
          SizedBox(height: 4.v),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatTealA40001,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 8.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatTealA40001,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatTealA40001,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatTealA40001,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 8.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
            ],
          ),
          SizedBox(height: 4.v),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 8.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 8.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
            ],
          ),
          SizedBox(height: 4.v),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 8.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 8.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
            ],
          ),
          SizedBox(height: 4.v),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 8.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 8.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
            ],
          ),
          SizedBox(height: 4.v),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 8.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 8.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
            ],
          ),
          SizedBox(height: 4.v),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 8.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 8.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
            ],
          ),
          SizedBox(height: 4.v),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 8.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 8.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
            ],
          ),
          SizedBox(height: 4.v),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatCyan300,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatCyan300,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 19.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 25.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatPrimary,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatCyan300,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 19.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeatCyan300,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
              CustomImageView(
                imagePath: ImageConstant.imgSeat,
                height: 2.v,
                width: 3.h,
                margin: EdgeInsets.only(left: 2.h),
              ),
            ],
          ),
          SizedBox(height: 7.v),
        ],
      ),
    );
  }
}
